name: SelfControl
version: '1.1.1'
main: cat6172.selfcontrol.SelfControl
description: Kick/tempban yourself at a specified time
author: Cat6172
api-version: '1.21'

commands:
  kickme:
    description: Add/remove yourself to the list of players kicked at specified time
    permission: selfcontrol.kick
    usage: /kickme at [time, ie 1:34pm] (to add) or /kickme r (to remove)
  banme:
    description: Add/remove yourself to the list of players temp banned (1 hour) at specified time
    permission: selfcontrol.ban
    usage: /banme set [time, ie 1:34pm] or /banme r (to remove)
permissions:
  selfcontrol.kick:
    description: add self to auto kick list
    default: true
  selfcontrol.ban:
    description: add self to temp ban list
    default: false
